/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import model.Person;
//import ulb.lisa.his.util.BeIDCard;

/**
 *
 * @author Adrien Foucart
 */
public class CreatePersonForm extends javax.swing.JPanel {
    
    Person currentPerson = null;
    
    /**
     * Creates new form CreatePersonForm
     */
    public CreatePersonForm() {
        this(null);
    }
    
    public CreatePersonForm(Person currentPerson){
        this.currentPerson = currentPerson;
        initComponents();
        
//        if( this.currentPerson != null || !BeIDCard.getInstance().hasCard() ) importFromIDButton.setEnabled(false);
//        else importFromIDButton.setEnabled(true);
    }
    
    public void setPerson(Person currentPerson){
        this.currentPerson = currentPerson;
        
        familyNameField.setText(currentPerson.getNameFamily());
        givenNameField.setText(currentPerson.getNameGiven());
        genderBox.setSelectedItem(currentPerson.getGender());
        SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        birthdateField.setText(fmt.format(currentPerson.getBirthdate()));
        nationalNumberField.setText(currentPerson.getNationalNumber());
        
//        if( currentPerson.getPhoto() != null ){
//            photoLabel.setIcon(new ImageIcon(currentPerson.getPhoto(), "Identity picture"));
//        }
    }
    
    public Person getPerson() {
        try {
            if( currentPerson == null ) currentPerson = new Person();
            
            currentPerson.setNameFamily(familyNameField.getText());
            currentPerson.setNameGiven(givenNameField.getText());
            currentPerson.setActive(true);
            currentPerson.setGender(genderBox.getSelectedItem().toString());
            SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            currentPerson.setBirthdate(fmt.parse(birthdateField.getText()));
            currentPerson.setNationalNumber(nationalNumberField.getText());
            
            return currentPerson;
        } catch (ParseException ex) {
            Logger.getLogger(CreatePersonForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importFromIDButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        familyNameField = new javax.swing.JTextField();
        givenNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        genderBox = new javax.swing.JComboBox<>();
        birthdateField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loadPhotoButton = new javax.swing.JButton();
        nationalNumberField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();

        importFromIDButton.setText("Import from eID");
        importFromIDButton.setEnabled(false);
        importFromIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importFromIDButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Family Name");

        jLabel3.setText("Given Name");

        jLabel4.setText("Gender");

        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        birthdateField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jLabel5.setText("Birthdate");

        jLabel6.setText("Photo");

        loadPhotoButton.setText("Load from file");
        loadPhotoButton.setEnabled(false);

        jLabel7.setText("National Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importFromIDButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(loadPhotoButton)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(familyNameField)
                            .addComponent(givenNameField)
                            .addComponent(birthdateField)
                            .addComponent(nationalNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(importFromIDButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(familyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(givenNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(birthdateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(loadPhotoButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nationalNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(photoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void importFromIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importFromIDButtonActionPerformed
//        this.setPerson(BeIDCard.getInstance().read());
    }//GEN-LAST:event_importFromIDButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField birthdateField;
    private javax.swing.JTextField familyNameField;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JTextField givenNameField;
    private javax.swing.JButton importFromIDButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton loadPhotoButton;
    private javax.swing.JTextField nationalNumberField;
    private javax.swing.JLabel photoLabel;
    // End of variables declaration//GEN-END:variables
}
